wallets:
  from_key: ${PRIVATE_KEY}
dotenv: .env
networks:
  goerli:
    wethAddress: '0xCCB14936C2E000ED8393A571D15A2672537838Ad'
  mainnet-fork:
    wethAddress: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
